# Generated by Django 3.0.6 on 2020-05-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_app', '0002_post_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_timestamp']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_timestamp']},
        ),
    ]
